# Generated by Django 3.2.7 on 2021-09-17 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cities_light', '0011_auto_20210917_1534'),
        ('store', '0002_auto_20210916_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=400)),
                ('zip', models.CharField(max_length=50)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cities_light.city')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cities_light.region')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
