# Generated by Django 3.2.7 on 2021-09-20 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_address_subregion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
    ]
