# Generated by Django 3.2.7 on 2021-09-21 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
