# Generated by Django 3.2.7 on 2021-09-21 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_delete_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartProduct',
        ),
    ]
